import type { Metadata } from "next";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import { Inter } from 'next/font/google'
import { Provider } from "react-redux";
import { store } from "@/store/store";
import ClientComponent from "./Provider";
import NProgressProvider from "@/components/Nprogress";

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.variable}
      >
        {/* <NProgressProvider /> */}
        <ClientComponent>{children}</ClientComponent>
      </body>
    </html>
  );
}
